name: Docker images for bookstore, bookbuyer and bookthief

on:
  push:
    branches: [main]

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Short the sha to 7 characters only
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::7})
      - name: Bookstore docker image
        uses: docker/build-push-action@v2
        with:         
          context: bookstore/         
          push: true
          tags: ghcr.io/0gis0/osm-aks-addon/bookstore:${{ steps.vars.outputs.tag }}
      - name: Bookbuyer docker image
        uses: docker/build-push-action@v2
        with:         
          context: bookbuyer/         
          push: true
          tags: ghcr.io/0gis0/osm-aks-addon/bookbuyer:${{ steps.vars.outputs.tag }}
      - name: Bookthief docker image
        uses: docker/build-push-action@v2
        with:         
          context: bookthief/         
          push: true
          tags: ghcr.io/0gis0/osm-aks-addon/bookthief:${{ steps.vars.outputs.tag }}